[package]
name = "fakexr"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
openxr-sys = { workspace = true }
openxr_mndx_xdev_space = "0.2"
paste = "1.0.15"
ash = { workspace = true }
crossbeam-utils = "0.8.20"
slotmap = { workspace = true }
glam = { workspace = true }
